steps:
  - command:
      - "yarn install"
      - "yarn run test"
    plugins:
      - docker#v3.11.0:
          image: "public.ecr.aws/s6w7s0y4/example-ecr-box-march-22:latest"
#          image: "mcr.microsoft.com/playwright:v1.20.0-focal"
          always-pull: true
          command: ["echo", "hello"]
          environment:
            - "MY_SECRET_KEY"
            - "MY_SPECIAL_BUT_PUBLIC_VALUE=kittens"
#steps:
#  - label: ":console:"
#    command: "echo 'Hello, World!'"
#    plugins:
#      - docker#v3.2.0:
#          image: "mcr.microsoft.com/playwright:v1.20.0-focal"
#          workdir: /app
#    parallelism: 1
#    agents:
#      queue: "${BUILDKITE_AGENT_META_DATA_QUEUE:-default}"
